### ISSUE TITLE
Ubunu 14.04 installer not working

### ISSUE THREAD

**Issue by shalandlord** [Sauermann/psopt-installer#8]
gets stuck in infinite loop when using ubuntu 14.04 installer during psopt installation phase
also i think the readme.md file needs to reflect the correct branch for the 14.04 installer and correct .sh file

**Comment by shalandlord** [comment]
readme.md says wget https://raw.github.com/Sauermann/psopt-installer/master/uppis.sh  however the "master" should be "ubu144" I think??? also is uppis.sh the correct script?

**Comment by shalandlord** [comment]
Upon further investigation I think SuiteSparse and CXSparese is not being downloaded from the latest link

**Comment by Sauermann** [comment]
Thanks for your comments.
Currenty Ubuntu 14.04 is not supported. That is also the reason why this experimental branch is not mentioned in the master-readme.
Last time I tried to install it, I had problems compiling a package, so for the moment I recommend using Ubuntu 12.04.

The CXSparse issue is known and already corrected for the other installers.

Will let this issue open until Ubuntu 14.04 is supported.

**Comment by shalandlord** [comment]
ok.
FYI
When I altered the 14-4 script with the fix for the CXSparse and SuiteSparse the way it is in the 12.04 script it seemed to have compiled and installed all the way in my Ubuntu 14.04 installation.
Is the 12.04 installer valid for Ubuntu 14.04 installation?


 
![screenshot from 2015-07-16 16 02 54](https://cloud.githubusercontent.com/assets/2389104/8728367/41f32ee2-2bd4-11e5-8561-0bc958895fa7.png)

**Comment by Sauermann** [comment]
Thanks for the info. I can't make any promises however when I will get time to tackle the Ubuntu 14.04 installer.

**Comment by Sauermann** [comment]
The new version of PSOPT4 already contains an installer for Ubuntu 14.04. So I will close this issue, since I will not provide an installer for the soon outdated PSOPT3.

**Comment by shalandlord** [comment]
Thank you for the uodate

**Comment by shalandlord** [comment]
Thank you for the update

**Comment by shalandlord** [comment]
Do you know when psopt 4 is released ?

**Comment by Sauermann** [comment]
No, I don't know the release date, but perhaps the location of the source-code repository, that already contains a prerelease, will help you:
https://github.com/PSOPT/psopt
